# Generated by Django 5.2.7 on 2025-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applicant_telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
