# Generated by Django 5.2.7 on 2025-10-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_applicant_telegram_id'),
        ('booking', '0004_booking_no_overlap'),
    ]

    operations = [
    ]
