# Generated by Django 5.2.7 on 2025-10-05 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YouthCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='centers/emblems/')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('responsible_name', models.CharField(blank=True, max_length=255)),
                ('responsible_phone', models.CharField(blank=True, max_length=50)),
                ('responsible_telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='centers.district')),
            ],
            options={
                'verbose_name': 'Молодёжный центр',
                'verbose_name_plural': 'Молодёжные центры',
                'ordering': ['district__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('RESP', 'Ответственный за помещение'), ('CENTER', 'Руководитель центра')], default='RESP', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='centers.youthcenter')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
